plugins {
    id "java"
    id "idea"
    id "org.jetbrains.intellij.platform" version "2.13.1"
    id "pl.allegro.tech.build.axion-release" version "1.21.1"
}

group "net.ashald"

scmVersion {
    tag {
        prefix = "v"
        versionSeparator = ""
    }
}

allprojects {
    apply plugin: 'java'
    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    repositories {
        mavenCentral()
    }

    project.version = scmVersion.version

    ext.jetbrains = [
            version : "2025.3",
            scala   : "org.intellij.scala:2025.3.26"
    ]
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

intellijPlatform {
    projectName = "EnvFile"
    buildSearchableOptions = false

    pluginConfiguration {
        name = "EnvFile"

        ideaVersion {
            sinceBuild = "243"
        }
    }

    pluginVerification {
        ides {
            recommended()
        }
    }
}

dependencies {
    intellijPlatform {
        intellijIdea(jetbrains.version)
        bundledPlugin("com.intellij.java")
    }

    implementation project(":envfile-products-idea")
    implementation project(":envfile-products-pycharm")
    implementation project(":envfile-products-rubymine")
    implementation project(":envfile-products-goland")
}

wrapper {
    gradleVersion = "9.2.1"
}
