pluginManagement {
    repositories {
        maven { url = uri("https://cache-redirector.jetbrains.com/plugins.gradle.org") }
        gradlePluginPortal()
    }
}

rootProject.name = 'envfile'

include (
        'modules/core',
        'modules/platform',
        'modules/products/idea',
        'modules/products/goland',
        'modules/products/pycharm',
        'modules/products/rubymine',
)

rootProject.children.each {
    it.name = (it.name.replaceFirst("modules/", "envfile/").replace("/", "-"))
}
