plugins {
    id "java"
    id "org.jetbrains.intellij.platform.module"
}

repositories {
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea(jetbrains.version)
        bundledPlugins(
            "com.intellij.java",
            "com.intellij.gradle",
            "org.jetbrains.idea.maven"
        )
        plugin(jetbrains.scala)
        instrumentationTools()
    }

    implementation project(":envfile-core")
    implementation project(":envfile-platform")
    implementation 'org.jetbrains:annotations:23.0.0'

    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}
