plugins {
    id "java"
    id "org.jetbrains.intellij.platform.module"
}

repositories {
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        goland(jetbrains.version)
        bundledPlugin("org.jetbrains.plugins.go")
    }

    implementation project(":envfile-platform")
    implementation 'org.jetbrains:annotations:23.0.0'

    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}
